on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        default: '0.0.0.0'
        required: true
        type: string
      create-release:
        type: boolean
        description: "Create Release"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: restore x86
      run: dotnet restore UNotePad -r win-x86

    - name: restore x64
      run: dotnet restore UNotePad -r win-x64

    - name: build x86
      run: dotnet publish UNotePad -c Release -r win-x86 --self-contained true -o bin/win-x86 /p:version=${{ inputs.version }}

    - name: build x64
      run: dotnet publish UNotePad -c Release -r win-x64 --self-contained true -o bin/win-x64 /p:version=${{ inputs.version }}

    - name: compress x86
      run: 7z a UNotePad-x86-${{ inputs.version }}.zip ./bin/win-x86/*

    - name: compress x64
      run: 7z a UNotePad-x64-${{ inputs.version }}.zip ./bin/win-x64/*

    - name: Upload artifact x64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: UNotePad-x64-${{ inputs.version }}.zip
        path: UNotePad-x64-${{ inputs.version }}.zip

    - name: Upload artifact x86
      uses: actions/upload-artifact@v1.0.0
      with:
        name: UNotePad-x86-${{ inputs.version }}.zip
        path: UNotePad-x86-${{ inputs.version }}.zip

    - name: Create release
      if: ${{ inputs.create-release }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        files: |
          UNotePad-x64-${{ inputs.version }}.zip
          UNotePad-x86-${{ inputs.version }}.zip
          